export const enum ChatNotificationReason {
  INVITATION = 'INVITATION',
  NEW_MESSAGE = 'NEW_MESSAGE',
  OFFENSIVE_MESSAGE = 'OFFENSIVE_MESSAGE',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  INVITATION_DENIED = 'INVITATION_DENIED',
  CRAU_JOINED = 'CRAU_JOINED',
  CRAU_LEAVE = 'CRAU_LEAVE'
}
